create table customer (id bigint generated by default as identity, address varchar(255), first_name varchar(255), last_name varchar(255), points integer, primary key (id))
create table customer_transaction (id bigint generated by default as identity, amount float, purchase_date timestamp, customer_id bigint not null, primary key (id))
alter table customer_transaction add constraint FKou0oeb7lao96n1axst4cck69i foreign key (customer_id) references customer
