version: "3"
services:
  server:
    image: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/customer?useSSL=false
    build:
      context: "./"
      dockerfile: "Dockerfile"
    networks:
      - springmysql-net
    depends_on:
      - mysqldb


  mysqldb:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data/mysql:/var/lib/mysql
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=customerdb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net:
